# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HaskerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.uniq_filename)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasker_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
